### ISSUE TITLE
block js not loading

### ISSUE THREAD

**Issue by johannesdold** [mainio/c5_free_cookies_disclosure#3] opened 2017-03-07 12:35 UTC
Hi, I have the problem, that the js files from the block are not loaded. I have tried both cases, using and not using a custom stack with the block. I searched a little and found that there might be problems  with hard coded blocks and autoloading the js/css assets from that block. I am using 5.7.5.9 right now. Any idea what might be the cause?

**Comment by ahukkanen** [comment] 2017-03-07 12:47
The assets are required in the `on_page_view` event:
https://github.com/mainio/c5_free_cookies_disclosure/blob/master/src/PackageServiceProvider.php#L89-L90

I'd look into that event's logic and first of all see whether the assets are required at all. In case they are not required, debug the logic in that event handler and see what might be the problem. In case they are loaded, look at what might have changed in the core.

In case you figure out that something has changed in the core about how they handle asset loading, we would obviously be interested in hearing back about this.

**Comment by johannesdold** [comment] 2017-03-07 13:10
Ok, found it. In line 90 in Src/PackageServiceProvider the js asset for the ajax_form is required. However, it is only loaded, if the hide_interval is set to something other than 0. I always had this setting set to 0, so I did not get the asset loaded. To me it seems, that the js asset disclosure_ajax_form should be loaded no matter what the value for the hide interval is.

**Comment by ahukkanen** [comment] 2017-03-08 09:05
OK cool. I think this is on purpose since if the hide interval is 0, it basically means the same as do not display the element in which case I see it logical that the JS is not even loaded.

**Comment by johannesdold** [comment] 2017-03-08 09:30
Hm, but in the description of the field it says: "n seconds (leave empty if you don't want to hide the notification)". To me this reads like it is shown forever (if the button is not clicked), if 0 is chosen. And it is also what happens...

**Comment by ahukkanen** [comment] 2017-03-08 09:44
Yeah, you are perfectly right, I'll reopen this issue.

The JS is correctly omitted for the hiding script but the problem is that the AJAX form script is not loaded either in this case. This would mean that this line would probably need to be changed outside of the if clause:
https://github.com/mainio/c5_free_cookies_disclosure/blob/master/src/PackageServiceProvider.php#L90

The CSS still seems to be properly loaded judging solely by reading the code.

But yeah, you are right about the AJAX form script which should be loaded in your case.

We'd be happy to welcome a pull request for this!

**Comment by ahukkanen** [comment] 2017-03-08 10:27
Fixed by #4. Many thanks @johannesdold !

**Closed as completed by ahukkanen** 2017-03-08 10:27 UTC
